baseurl: ""  #/studentenfutter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      headerTitle: "Rezepte"
      image: "/assets/images/default.png"
  - scope:
      path: ""
    values:
      layout: "default"