
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      headerTitle: "Rezepte"
  - scope:
      path: ""
    values:
      layout: "default"

prose:
  rooturl: '_posts'
  #siteurl: 'http://prose.github.io/starter/'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  #media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _post:
      - name: "layout"
      field:
        element: "hidden"
        value: "default"
      - name: "title"
        label: "Titel"
        value: ""
      - name: "categories"
        label: "Kategorie hinzufügen"
        placeholder: "Kategorie auswählen"
        ootions:
          - name: "Schnell"
            value: "schnell"
          - name: "Vegetarisch"
            value: "vegetarisch"
