# docker run --rm --volume="%cd%:/srv/jekyll" -p 4000:4000 jekyll/jekyll:4.0 jekyll serve --force_polling

version: '3'
services: 
  jekyll-serve:
    image: jekyll/jekyll:4.0
    volumes:
      - ".:/srv/jekyll"
    ports:
    - 4000:4000
    command: 'jekyll serve --force_polling'